name: "badboy_"
profile:
  web: "https://fnordig.de"
  twitter: "badboy_"
  gravatar: "dd016fe8d3b2f44d2c9c5f3367b3ad25"
hasbeen:
  cities:
    - "Aachen"
    - "Kamen"
    - "Dortmund"
    - "Hamburg"
    - "Honolulu"
    - "Leipzig"
    - "Cologne"
    - "Berlin"
    - "Paris"
    - "Malaga"
    - "Oslo"
    - "St. Augustin"
    - "San Francisco"
    - "Moskau"
    - "New York"
    - "Bejing"
    - "Dalian"
    - "Pisa"
    - "Šibenik"
    - "Mailand"
    - "Zurich"
    - {"Dublin": "Dublin, Ireland"}
    - "Salzburg"
    - "Stavanger"
    - "London"
    - "Budapest"
    - "Bodø"
    - {"Å": "Å, Norway"}
    - "Svolvær"
    - "Tromsø"
    - "Trondheim"
    - "Vancouver"
    - "Bowser"
    - "Tofino"
    - "Penticton"
    - "Jasper"
    - "Grande Prairie"
    - "Edmonton"
    - "Amsterdam"
    - "Stockholm"
    - "Bochum"
