name: "badboy_"
profile:
  web: "https://fnordig.de"
  twitter: "badboy_"
  gravatar: "dd016fe8d3b2f44d2c9c5f3367b3ad25"
hasbeen:
  cities:
    - "Aachen"
    - "Kamen"
    - "Dortmund"
    - "Hamburg"
    - "Honolulu"
    - "Leipzig"
    - "Cologne"
    - "Berlin"
    - "Paris"
    - "Malaga"
    - "Oslo"
    - "St. Augustin"
    - "San Francisco"
    - "Moskau"
    - "New York"
    - "Bejing"
    - "Dalian"
    - "Pisa"
    - "Å ibenik"
    - "Mailand"
    - "Zurich"
    - "Dublin"
    - "Salzburg"
