name: "ben"
profile:
  web: "http://benjaminknofe.com"
  twitter: "bknofe"
  gravatar: "6aed6a0dfa09b46d6fbd5149eb56def8"
hasbeen:
  cities:
    - "Amiens"
    - "Antalya"
    - "Berlin"
    - "Bradenton"
    - "Bremen"
    - "Copenhagen"
    - "Dortmund"
    - "Dresden"
    - "Grignan"
    - "Gräfenroda"
    - "Hamburg"
    - "Hammamet"
    - "Hvide Sande"
    - "Jena"
    - "Jerusalem"
    - "Jönköping"
    - "Karlsruhe"
    - "Kempten (Allgäu)"
    - "Kyriat Ono"
    - "Leipzig"
    - "Lemvig"
    - "London"
    - "Malmö"
    - "Mundelsheim"
    - "Nuremberg"
    - "Prag"
    - "Stuttgart"
    - "Tel Aviv-Yafo"
    - "Verona"
    - "Würzburg"
    - {"La Tremblade": "La Tremblade, Frankreich"}
    - {"Lanzarote": "Lanzarote, Arrecife, Spanien"}
    - {"Stockholm": "Stockholm, Schweden"}
    - {"Tokio": "Tokio, Japan"}
    - {"Visby": "Visby, Gotland, Schweden"}
