name: "Bitboxer"
profile:
  web: "http://bodotasche.de"
  twitter: "bitboxer"
  gravatar: "51968c9632cc07ab399cc32412ccbb98"
hasbeen:
  cities:
    - "Alcúdia"
    - "Amsterdam"
    - "Barcelona"
    - "Berlin"
    - "Bologna"
    - "Boston"
    - "Bryce"
    - "Eindhoven"
    - "Enschede"
    - "Ferropolis"
    - "Flagstaff"
    - "Frankfurt"
    - "Freiburg"
    - "Fresno"
    - "Granada"
    - "Hamburg"
    - "Hurghada"
    - "Kairo"
    - "Kennedy Space Center"
    - "Key West"
    - "Köln"
    - "Las Vegas"
    - "Los Angeles"
    - "Maastricht"
    - "Miami"
    - "Montreal"
    - "München"
    - "Münster"
    - "New York"
    - "Niagara Falls"
    - "Oldenburg"
    - "Orlando"
    - "Osnabrück"
    - "Page"
    - "Paris"
    - "Pittsburgh"
    - "Prag"
    - "San Francisco"
    - "Sevilla"
    - "Shippensburg"
    - "Toronto"
    - "Washington"
    - "Wien"
    - "Worms"
    - "Würzburg"
