name: "captainhagbard"
profile:
  web: "http://schilling.io"
  twitter: "captainhagbard"
  gravatar: "0d538506cb7d350250906243645c28d4"
hasbeen:
  cities:
    - "Berlin"
    - "New York"
    - "San Francisco"
    - "Los Angeles"
    - "Las Vegas"
    - "Paris"
    - "Washington D.C."
    - "Athen"
    - "Thessaloniki"
    - "Köln"
    - "Hamburg"
    - "Bochum"
    - "Dortmund"
    - "Wrocław"
    - "München"
    - "Frankfurt"
    - "Amsterdam"
    - "Kraków"
    - "Kreta"
    - "Playa de Alcúdia"
    - "Salzburg"
    - "Fehmarn"
    - "Juist"
    - "Langeoge"
    - "Wangerooge"
    - "Borkum"
    - "Norderney"
    - "Detmold"
