name: "eljojo"
profile:
  web: "http://eljojo.net"
  twitter: "eljojo"
  gravatar: "570a76d7545a0ae4b693ffee5435717e"
hasbeen:
  cities:
    - "Ottawa"
    - {"Berlin": "Berlin, Germany"}
    - {"Santiago": "Santiago, Chile"}
    - "Chillán"
    - "Toronto"
    - "Montréal"
    - "New Orleans"
    - "Buffalo"
    - "Oxford"
    - "Marrakesh"
    - "Málaga"
    - "Barcelona"
    - {"Paris": "Paris, France"}
    - "Amsterdam"
    - "Steenwijk"
    - "Köln"
    - "Essen"
    - "Copenhagen"
    - "Magdeburg"
    - "Munich"
    - "Dresden"
    - "Salzburg"
    - "Prague"
    - "Wrocław"
    - "Warsaw"
    - "Kraków"
    - {"Athens": "Athens, Greece"}
    - "Antalya"
    - "Hiroshima"
    - "Osaka"
    - "Kyoto"
    - "Tokyo"
    - "Machu Picchu"
    - "Cuzco"
    - "San Pedro de Atacama"
    - "Antofagasta"
    - "Mendoza"
    - "Concepción"
    - "Temuco"
    - "Valdivia"
    - "Bariloche"
    - "Puerto Montt"
