name: "schultyy"
profile:
  web: "http://hasbeen.at/neinasaservice"
  twitter: "schultyy"
  gravatar: "8fb4c4eea4580647ac37881cec8606aa"
hasbeen:
  cities:
    - "Hamburg"
    - "Dortmund"
    - "Cologne"
    - "Wrocław"
    - "Berlin"
    - "Arnsberg"
    - "Bochum"
    - "Hannover"
    - "Regensburg"
    - "Münster"
    - "Duisburg"
    - "Leipzig"
    - "Munich"
    - "Vienna"
