name: "Skade"
profile:
  web: "http://asquera.de"
  twitter: "argorak"
  gravatar: "1c88d7906e3ffa450aedff2f5f1d1299"
hasbeen:
  cities:
    - "Speyer"
    - "Hamburg"
    - "München"
    - "Berlin"
    - "Köln"
    - "Buenos Aires"
    - "Lobatse"
    - "Gaborone"
    - "St. John's"
    - "Amsterdam"
    - "Copenhagen"
    - "Sophia-Antipolis"
    - "Leipzig"
    - "Vienna"
    - "Dublin"
    - "Tokyo"
    - "Osaka"
    - "Toronto"
    - "Niagara Falls"
    - "Kasane"
    - {"Livingstone": "Livingstone, Southern, Zambia"}
    - "Paris"
    - "St-Malo"
    - "Lorient"
    - "Nice"
    - "Marrakesh"
    - "Rome"
    - "Santa Cruz de Tenerife"
    - "Stockholm"
    - "Turku"
    - "Helsinki"
    - "Barcelona"
    - "Marseille"
    - "Reims"
    - "Lisboa"
    - "Faro"
    - "Ghanzi"
    - "Montreal"
    - "Québec"
    - "Prague"
    - "Wrocław"
    - "Poznan"
    - "Kraków"
    - "Oulu"
    - "Rovaniemi"
    - "Victoria Falls"
    - "Pretoria"
    - "Bastia"
    - "Corte"
    - "Athens"
    - "Patra"
    - "Verbier"
    - "Les Menuiers"
    - "Monaco"
    - "Pfaffenbronn"
    - "San Pellegrino"
    - "São Paulo"
    - "Edinburgh"
    - "Glasgow"
    - "London"
    - "Kyle of Lochalsh"
    - "Crieff"
    - "Inverness"
    - "Montevideo"