name: "sternenseemann"
profile:
  web: "http://lukasepple.de"
  twitter: "lukasepple"
  gravatar: "551cf7b2e59fe8944d21be722d619396"
hasbeen:
  cities:
    - "Augsburg"
    - "Berlin"
    - "Schwerin"
    - "Hamburg"
    - "MÃ¼nchen"
    - "Rom"
    - "Paris"
    - "Prag"
    - "Lissabon"
    - "Ulten"
